app.id=com.melih.kmptemplate
app.name=KMP Template
app.versionCode=1
app.versionName=1.0.0
app.buildType=debug
app.isDebuggable=true
#
#signing.android.release.storeFilePath=../tools/release.jks
#signing.android.release.storePassword=
#signing.android.release.keyAlias=
#signing.android.release.keyPassword=
#
#tmdb.apiKey=
#
## By default testCoverage is not run - this will safe time when running tests locally.
## https://jeroenmols.com/blog/2016/09/01/coveragecost/
#isTestCoverageEnabled=false

# For test automation having leak canary enabled is undesireable. So therefore it is configurable.
#leakCanaryEnabled=true
