# Extra detekt config to change the default one.
naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  ObjectPropertyNaming:
    active: true
    # Suppressing ObjectPropertyName does not work, ignoring it in config level
    excludes: ['**/LocalAppLocaleIso.wasmJs.kt']

style:
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'DevicePreviews', 'Preview' ]
  MaxLineLength:
    excludes: [ "**/test/**","**/androidTest/**" ]
  MagicNumber:
    excludes: [ "**/test/**","**/androidTest/**" ]
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  ForbiddenComment:
    active: false