name: Build Android app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    # Only run build in template repo
    if: github.event.repository.name == 'KMP-Template' && github.repository_owner == 'melomg'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Android debug build
        run: ./gradlew assembleDebug --stacktrace
