name: Build & Deploy to Firebase

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build AAB (staging flavor)
        run: ./gradlew bundleStaging

      - name: Upload ProGuard mapping file to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase.json
        run: |
          firebase crashlytics:upload-proguard \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --mapping composeApp/build/outputs/mapping/staging/mapping.txt

      - name: Distribute to Firebase
        uses: ./.github/actions/firebase-distribute
        with:
          app-path: composeApp/build/outputs/bundle/staging/composeApp-staging.aab
          firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}
          service-account-json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          groups: "qa-team"
          release-notes: "Deployed Staging Android App automatically via GitHub Actions 🚀"
